image_width: 1280
image_height: 960
camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [963.304385, 0.000000, 637.039646, 0.000000, 965.910111, 479.796409, 0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.411342, 0.158145, 0.000504, 0.000315, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000]
projection_matrix:
  rows: 3
  cols: 4
  data: [758.520081, 0.000000, 636.003326, 0.000000, 0.000000, 855.257141, 479.825755, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]
